# Generated by Django 3.0.8 on 2020-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200710_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
