# Generated by Django 3.0.8 on 2020-07-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200710_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id',
            new_name='placeID',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='placeName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='userContact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='userRole',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='tagid',
            new_name='tagID',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='id',
            new_name='visitID',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='userid',
        ),
        migrations.AddField(
            model_name='visit',
            name='placeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_placeID', to='api.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_userID', to='api.User'),
            preserve_default=False,
        ),
    ]
