# Generated by Django 3.0.8 on 2020-07-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200710_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='placeID',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='userID',
        ),
        migrations.AddField(
            model_name='visit',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_visits', to='api.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_visits', to='api.User'),
            preserve_default=False,
        ),
    ]
