# Generated by Django 3.0.8 on 2020-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_userphotourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placePhotoUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
