# Generated by Django 3.0.8 on 2020-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='tagID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='tagID',
            field=models.CharField(max_length=20),
        ),
    ]
