# Generated by Django 3.1 on 2020-10-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201011_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='tagID',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='tagID',
            new_name='tag',
        ),
    ]
