# Generated by Django 3.1 on 2020-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201012_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='inCloseContact',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
