# Generated by Django 3.0.8 on 2020-10-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagToToken',
            fields=[
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Tag')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
